name: "Personal Corne"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      custom_config: '["#define MIRYOKU_NAV_INVERTEDT"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y"]'
